In [1]:
#Dependencies
from matplotlib import pyplot as plt
import pandas as pd
import sklearn
from sklearn.preprocessing import LabelEncoder, MinMaxScaler
from sklearn.preprocessing import OneHotEncoder
from sklearn.cluster import KMeans
from sklearn.metrics import balanced_accuracy_score
from sklearn.metrics import confusion_matrix
from imblearn.metrics import classification_report_imbalanced

In [2]:
#read csv into df
df = pd.read_csv("Levels_Fyi_Salary_Data 2.csv")
# columns to drop... salary_currency, salary, work_year
df.sample(25)

timestamp     company                           level  \
49616   4/26/2021 10:13:54         PNC  Technology Development Program   
62053   7/13/2018 14:38:27      Amazon                               6   
52363   5/25/2021 10:06:58       Match          Lead Software Engineer   
23161   6/26/2020 23:44:30      Amazon                             IC6   
6664    5/21/2019 22:22:42  Salesforce                             MTS   
56288    7/1/2021 10:32:11   Microsoft                              67   
12476  10/28/2019 20:42:51        Uber                               4   
61301   8/12/2021 21:49:29      Square                         Level 4   
46128    3/26/2021 7:16:32       Intel                         Grade 9   
9348      8/1/2019 3:47:08     Expedia                               L   
16473   2/11/2020 16:21:05    T-Mobile              Associate Engineer   
21474   5/23/2020 23:57:41   Capgemini                          Senior   
14811    1/10/2020 9:08:50     Twitter                           PM II   
116    12/29/2017 14:37:52        EPAM                          Senior   
5829     4/16/2019 8:21:43      Amazon                              L5   
8511     7/9/2019 12:11:37   Bloomberg               Software Engineer   
49437   4/23/2021 23:20:37        Visa        Senior Software Engineer   
7170    6/11/2019 15:57:23      Amazon                          L6 SDM   
646     7/27/2018 12:05:02      Amazon                              L6   
39780   1/19/2021 16:25:37      Google                              L5   
6548    5/17/2019 16:49:16   Atlassian                              P5   
42047   2/14/2021 23:38:46    Facebook                              E6   
47545    4/8/2021 10:48:21      Amazon                              L5   
15311   1/20/2020 22:35:25   Pinterest                              L3   
18954    4/1/2020 13:28:17     Comcast       Senior Principal Engineer   

                              title  totalyearlycompensation  \
49616             Software Engineer                    85000   
62053  Software Engineering Manager                   500000   
52363             Software Engineer                   140000   
23161               Product Manager                   225000   
6664              Software Engineer                   178000   
56288  Software Engineering Manager                   480000   
12476             Software Engineer                   263000   
61301             Software Engineer                   233000   
46128              Product Designer                   290000   
9348              Software Engineer                   196000   
16473             Software Engineer                    95000   
21474             Software Engineer                   114000   
14811               Product Manager                   253000   
116               Software Engineer                    30000   
5829              Software Engineer                   239000   
8511              Software Engineer                   160000   
49437             Software Engineer                   126000   
7170   Software Engineering Manager                   297000   
646                 Product Manager                   400000   
39780             Software Engineer                   382000   
6548              Software Engineer                   145000   
42047             Software Engineer                   570000   
47545             Software Engineer                   223000   
15311             Software Engineer                   172000   
18954             Software Engineer                   240000   

                      location  yearsofexperience  yearsatcompany  \
49616           Pittsburgh, PA                0.0             0.0   
62053              Seattle, WA               20.0            16.0   
52363               Dallas, TX               11.0             5.0   
23161              Seattle, WA               11.0             3.0   
6664         San Francisco, CA                0.0             0.0   
56288        

In [3]:
df.nunique()


timestamp                  62561
company                     1631
level                       2923
title                         15
totalyearlycompensation      893
location                    1050
yearsofexperience             65
yearsatcompany                81
tag                         3058
basesalary                   482
stockgrantvalue              612
bonus                        335
gender                         4
otherdetails               12841
cityid                      1045
dmaid                        149
rowNumber                  62642
Masters_Degree                 2
Bachelors_Degree               2
Doctorate_Degree               2
Highschool                     2
Some_College                   2
Race_Asian                     2
Race_White                     2
Race_Two_Or_More               2
Race_Black                     2
Race_Hispanic                  2
Race                           5
Education                      5
dtype: int64

In [4]:
titles_df = df[df["title"]=="Data Scientist"]
titles_df


timestamp    company                        level  \
419     6/5/2018 14:06:30   LinkedIn                       Senior   
440      6/8/2018 9:49:25  Microsoft                           64   
444     6/8/2018 17:55:09       ebay                           26   
454    6/10/2018 19:39:35    Twitter                        Staff   
495    6/17/2018 11:39:38   Facebook                            5   
...                   ...        ...                          ...   
62240  3/26/2019 17:25:02        IBM                            8   
62283  6/17/2018 21:07:18   Facebook                           E3   
62285  7/16/2018 20:11:40        ADP           Sr UX Researcher 4   
62529  6/12/2018 20:54:06     Google                           T6   
62623  8/19/2018 20:31:37   Illumina  Bioinformatics Scientist II   

                title  totalyearlycompensation                  location  \
419    Data Scientist                   233000         San Francisco, CA   
440    Data Scientist                   218000               Seattle, WA   
444    Data Scientist                   180000              San Jose, CA   
454    Data Scientist                   500000         San Francisco, CA   
495    Data Scientist                   370000               Seattle, WA   
...               ...                      ...                       ...   
62240  Data Scientist                   155000            Washington, DC   
62283  Data Scientist                   150000  Singapore, SG, Singapore   
62285  Data Scientist                   185000              Roseland, NJ   
62529  Data Scientist                   685000              Kirkland, WA   
62623  Data Scientist                   175000             San Diego, CA   

       yearsofexperience  yearsatcompany             tag  basesalary  ...  \
419                  4.0             0.0   Data Analysis    162000.0  ...   
440                 11.0            11.0         ML / AI    165000.0  ...   
444                 10.0             5.0             NaN         0.0  ...   
454                  4.0             4.0         ML / AI    200000.0  ...   
495                  8.0             3.0             NaN    190000.0  ...   
...                  ...             ...             ...         ...  ...   
62240                5.0             2.0         ML / AI    141000.0  ...   
62283                0.0             0.0         ML / AI    150000.0  ...   
62285                8.0             2.0     UX Research    150000.0  ...   
62529               22.0             2.0         ML / AI    221000.0  ...   
62623                6.0             2.0  Bioinformatics    135000.0  ...   

       Doctorate_Degree  Highschool Some_College Race_Asian  Race_White  \
419                   0           0            0          0           0   
440                   0           0            0          0           0   
444                   0           0            0          0           0   
454                   0           0            0          0           0   
495                   0           0            0          0           0   
...                 ...         ...          ...        ...         ...   
62240                 0           0            0          0           0   
62283                 0           0            0          0           0   
62285                 0           0            0          0           0   
62529                 0           0            0          0           0   
62623                 0           0            0          0           0   

       Race_Two_Or_More  Race_Black  Race_Hispanic  Race  Education  
419                   0           0              0   NaN        NaN  
440                   0           0              0   NaN        NaN  
444                   0           0              0   NaN        NaN  
454                   0           0              0   NaN        NaN  
495                   0           0              0   NaN        NaN  
...                 ...     

In [5]:
locations = titles_df["location"]
locations.value_counts()

San Francisco, CA    373
Seattle, WA          311
New York, NY         245
Redmond, WA          105
Menlo Park, CA        94
                    ... 
Columbia, MO           1
Campbell, CA           1
Italy, TX              1
Titusville, NJ         1
Roseland, NJ           1
Name: location, Length: 225, dtype: int64

In [6]:
clean_df= titles_df.drop(columns=['timestamp', 'level', 'yearsatcompany', 'otherdetails','Doctorate_Degree', 'Bachelors_Degree',
                              'Highschool', 'Some_College', 'Race_Asian', 'Race_White', 'Race_Two_Or_More', 'Race_Black',
                              'Race_Hispanic', 'Race', 'Education','cityid','dmaid','rowNumber','Masters_Degree','tag','bonus','stockgrantvalue','basesalary','title'])
clean_df.head()
#get_dummies/oneHotEncoder on company size and employment type

company  totalyearlycompensation           location  yearsofexperience  \
419   LinkedIn                   233000  San Francisco, CA                4.0   
440  Microsoft                   218000        Seattle, WA               11.0   
444       ebay                   180000       San Jose, CA               10.0   
454    Twitter                   500000  San Francisco, CA                4.0   
495   Facebook                   370000        Seattle, WA                8.0   

     gender  
419    Male  
440    Male  
444  Female  
454    Male  
495    Male

In [7]:
clean_df.nunique()

company                    467
totalyearlycompensation    420
location                   225
yearsofexperience           28
gender                       3
dtype: int64

In [11]:
print(clean_df["company"].value_counts().head(10))

Amazon          257
Microsoft       217
Facebook        184
Google           89
Apple            78
IBM              66
Uber             60
Capital One      47
Walmart Labs     41
LinkedIn         36
Name: company, dtype: int64


In [27]:
#Binning he companies- .cut with 5 bins...do we want to specifically design these?
bin_labels = ['Small', 'Medium', 'Large', 'Very Large']
bins4 = clean_df['company'].value_counts()
company_bins = pd.cut(bins4, bins=4, labels=bin_labels).to_list()#does this solve the issue of imbalanced data?
company_bins

['Very Large',
 'Very Large',
 'Large',
 'Medium',
 'Medium',
 'Medium',
 'Small',
 'Small',
 'Small',
 'Small',
 'Small',
 'Small',
 'Small',
 'Small',
 'Small',
 'Small',
 'Small',
 'Small',
 'Small',
 'Small',
 'Small',
 'Small',
 'Small',
 'Small',
 'Small',
 'Small',
 'Small',
 'Small',
 'Small',
 'Small',
 'Small',
 'Small',
 'Small',
 'Small',
 'Small',
 'Small',
 'Small',
 'Small',
 'Small',
 'Small',
 'Small',
 'Small',
 'Small',
 'Small',
 'Small',
 'Small',
 'Small',
 'Small',
 'Small',
 'Small',
 'Small',
 'Small',
 'Small',
 'Small',
 'Small',
 'Small',
 'Small',
 'Small',
 'Small',
 'Small',
 'Small',
 'Small',
 'Small',
 'Small',
 'Small',
 'Small',
 'Small',
 'Small',
 'Small',
 'Small',
 'Small',
 'Small',
 'Small',
 'Small',
 'Small',
 'Small',
 'Small',
 'Small',
 'Small',
 'Small',
 'Small',
 'Small',
 'Small',
 'Small',
 'Small',
 'Small',
 'Small',
 'Small',
 'Small',
 'Small',
 'Small',
 'Small',
 'Small',
 'Small',
 'Small',
 'Small',
 'Small',
 'Small',
 'Small

In [33]:
#change company name to bin name
companies = []
for company in clean_df['company']:
    if company == "Amazon" or company == "Microsoft":
        company = "Very Large"
    elif company == "Facebook":
        company = "Large"
    elif company == "Google" or company == "Apple" or company == "IBM":
        company = "Medium"
    else:
        company = "Small"
    companies.append(company)

In [82]:
#reassign company column to bin name
clean_bins_df = clean_df.copy()
clean_bins_df['company'] = companies
clean_bins_df.head(10)
clean_bins_df['gender'].value_counts()

Male      1357
Female     361
Other       22
Name: gender, dtype: int64

In [72]:
#is their linearity between location numerical representation and salary?
clean_bins2 = clean_bins_df.drop(['location'], axis = 1)
locations = clean_bins_df['location']
clean_bins2.head()

company  totalyearlycompensation  yearsofexperience  gender
419       Small                   233000                4.0    Male
440  Very Large                   218000               11.0    Male
444       Small                   180000               10.0  Female
454       Small                   500000                4.0    Male
495       Large                   370000                8.0    Male

In [73]:
#Create label Encoder and encode categorical
from sklearn.preprocessing import LabelEncoder
lb_make = LabelEncoder()
clean_bins2['company']= lb_make.fit_transform(clean_bins2['company'])
clean_bins2['gender']= lb_make.fit_transform(clean_bins2['gender'])
clean_bins2.head()

company  totalyearlycompensation  yearsofexperience  gender
419        2                   233000                4.0       1
440        3                   218000               11.0       1
444        2                   180000               10.0       0
454        2                   500000                4.0       1
495        0                   370000                8.0       1

In [76]:
clean_bins2['gender'].value_counts() #what do we do with 4 genders?

1    1357
3     838
0     361
2      22
Name: gender, dtype: int64

In [68]:
#OneHot to new categories
from sklearn.preprocessing import OneHotEncoder
enc = OneHotEncoder(sparse=False)
company_encoded = lb_make.fit_transform(clean_bins2['company'])
company_encoded = company_encoded.reshape(len(company_encoded), 1)
onehot_company_encoded = enc.fit_transform(company_encoded)
print(onehot_company_encoded)

[[0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 1. 0.]
 ...
 [0. 0. 1. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]


In [69]:
# clean_bins_enc = .copy()
# clean_bins_enc['company'] = onehot_company_encoded
# clean_bins_enc.head()

SyntaxError: invalid syntax (749818807.py, line 1)

In [83]:
#skip procedural with get_dummies()?
# clean_dummies = clean_dummies.drop(['gender_2'], axis=1)
clean_dummies = pd.get_dummies(data=clean_bins2, columns=['company', 'gender'])#drop the gender columns?
clean_dummies.head(15)

totalyearlycompensation  yearsofexperience  company_0  company_1  \
419                   233000                4.0          0          0   
440                   218000               11.0          0          0   
444                   180000               10.0          0          0   
454                   500000                4.0          0          0   
495                   370000                8.0          1          0   
499                   200000                3.0          0          0   
509                   340000               11.0          0          0   
510                   690000               10.0          0          1   
513                   600000                3.0          0          0   
523                   168000                8.0          0          0   
535                   187000                4.0          0          0   
570                   225000               11.0          1          0   
668                   220000                6.0          0          0   
673                   130000                7.0          0          0   
740                   112000                4.0          0          0   

     company_2  company_3  gender_0  gender_1  gender_2  gender_3  
419          1          0         0         1         0         0  
440          0          1         0         1         0         0  
444          1          0         1         0         0         0  
454          1          0         0         1         0         0  
495          0          0         0         1         0         0  
499          0          1         0         1         0         0  
509          0          1         0         1         0         0  
510          0          0         0         1         0         0  
513          1          0         0         1         0         0  
523          1          0         0         1         0         0  
535          1          0         0         1         0         0  
570          0          0         0         0         0         1  
668          1          0         0         0         0         1  
673          0          1         0         0         0         1  
740          1          0         0         0         0         1

In [78]:
X = clean_dummies.drop(columns=["totalyearlycompensation"])
y = clean_dummies["totalyearlycompensation"]
X.shape
# Scale the dataset using MinMaxScaler()
X_scaled = MinMaxScaler().fit_transform(X)
X_scaled

array([[0.11764706, 0.33333333, 0.        , 0.        , 1.        ,
        0.        ],
       [0.32352941, 0.33333333, 0.        , 0.        , 0.        ,
        1.        ],
       [0.29411765, 0.        , 0.        , 0.        , 1.        ,
        0.        ],
       ...,
       [0.23529412, 0.33333333, 0.        , 0.        , 1.        ,
        0.        ],
       [0.64705882, 0.33333333, 0.        , 1.        , 0.        ,
        0.        ],
       [0.17647059, 1.        , 0.        , 0.        , 1.        ,
        0.        ]])

In [79]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X_scaled, 
                                                    y, 
                                                    random_state=42)

In [ ]:
# from sklearn.datasets import make_regression

# n_features = 3
# X, y = make_regression(n_features=n_features, 
#                        n_informative=n_features, random_state=1, 
#                        noise=0.5, bias=100.0)
# print(X.shape)

In [ ]:
# from mpl_toolkits.mplot3d import Axes3D
# fig = plt.figure(1, figsize=(5, 5))
# axes = Axes3D(fig, elev=20, azim=45)
# axes.scatter(X[:,0], X[:,1], X[:,2], c=y, cmap=plt.cm.get_cmap("Spectral"))
# plt.show()


In [80]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()

# Fitting our model with all our features in X
model.fit(X_train, y_train)
training_score = model.score(X_train, y_train)
testing_score = model.score(X_test, y_test)


print(f"Training Score: {training_score}")
print(f"Testing Score: {testing_score}")

Training Score: 0.15494256360154512
Testing Score: 0.16597498001429778


In [ ]:
# #Residuals
# predictions = model.predict(X)
# # Plot Residuals
# plt.scatter(predictions, predictions - y)
# plt.hlines(y=0, xmin=predictions.min(), xmax=predictions.max())
# plt.show()


In [90]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, 
                                                    y, 
                                                    random_state=42)

In [91]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.datasets import make_regression
# Fitting Random Forest Regression to the dataset
# import the regressor
from sklearn.ensemble import RandomForestRegressor
 
 # create regressor object
regressor = RandomForestRegressor(n_estimators = 100, random_state = 42)
 
# fit the regressor with x and y data
regressor.fit(X, y) 

RandomForestRegressor(random_state=42)

In [92]:
Y_pred = regressor.predict(X_test)  # test the output by changing values


In [94]:
training_score = regressor.score(X_train, y_train)
testing_score = regressor.score(X_test, y_test)


print(f"Training Score: {training_score}")
print(f"Testing Score: {testing_score}")

Training Score: 0.25946769966654326
Testing Score: 0.28260620926837376
